apiVersion: v1
kind: ConfigMap
metadata:
  name: ecomm-configmap
data:
  MONGODB_URL: "mongodb.roboshop.internal"
  ENV: dev
  BATCH: "54" 
  APP: ecomm 
  DEV: mikel

--- 

apiVersion: v1
kind: Pod
metadata:
  name: centos-with-cm 
spec:
  containers:
  - name: centos
    image: centos:8
    command: ["sleep" , "1000"]
    envFrom:
      - configMapRef: 
          name: ecomm-configmap

--- 
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-with-cm 
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["sleep" , "1000"]
    envFrom:
      - configMapRef: 
          name: ecomm-configmap