apiVersion: v1
kind: Secret 
metadata:
  name: ecomm-secrets
data:
  MONGODB_USERNAME: YWRtaW4K
  MONGODB_PASSWORD: bW9uZ28xMzIzNGRiCg==
  ECOMM_API_TOKEN: asdf24ewfdqweffaxdsadf

--- 

apiVersion: v1
kind: Pod
metadata:
  name: centos-with-secrets
spec:
  containers:
  - name: centos
    image: centos:7
    command: ["sleep" , "1000"]
    envFrom:
      - secretRef: 
          name: ecomm-secrets